apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  host: 34.107.36.218
  port: "3306"
  claimsDbName: claims
  membershipDbName: membership
  profileDbName: profile
  notificationDbName: notification
  ticketingDbName: ticketing
  keycloakDbName: keycloakDb
  stagingDbName: staging
  config.version: "002"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
data:
  username: cm9vdA==
  password: TEtHeE5EdHduRTM5bEJGcg==
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
data:
  username: bGN0LWFkbWlu
  password: bGN0LWFkbWluLXNlY3JldA==
type: Opaque