apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:15.1.0
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: password
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: keycloakDbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: DB_VENDOR
              value: MYSQL
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'

          ports:
            - name: jgroups
              containerPort: 7600
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080

#          resources:
#            requests:
#              cpu: 250m
#              memory: 2048Mi
#            limits:
#              cpu: 500m
#              memory: 8192Mi
