server:
  port: 8088

spring:
  datasource:
#    url: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maxLifetime: 3000
      maximumPoolSize: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  codec:
    max-in-memory-size: 50MB

  jackson:
    serialization:
      write_dates_as_timestamps: false

  camel:
    dataformat:
      json-jackson:
        auto-discover-object-mapper: true

lct-africa:
  notification:
    baseUrl: "http://notification-service:8080/api/v1/notification"
    sms-endpoint: "/sms"
    email-attachment-endpoint: "/mail/attachment"
    email-plain-endpoint: "/mail"
  member:
    search:
      url: "http://membership-service:8070"
  claims:
    url: "http://claims-service:8088"
    start_visit:
      url: "/lct/start_visit"
    get_open_transactions:
      url: "/lct/get_open_transactions"
    close_open_transaction:
      url: "/lct/close_open_transaction"
    agakhanNairobi: "/compas/lct/akuh/memberVerification/save_verified_lct_member"
  staging:
    url: "http://staging-service:8080/api/v1/staging/claim"
  britam:
    url: "https://apitest.britam.com/MedicalClaims/ProxyServices/MedicalClaimsProxyServiceRS/claim"
  liaison:
    url: ""
  document:
    url: "http://localhost:8095/api/file/download"


springdoc:
  api-docs:
    path: /v3/api-docs


