server:
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://localhost:3309/claims
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 31875595
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

  camel:
    dataformat:
      json-jackson:
        auto-discover-object-mapper: true

  server:
    error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false
#  kafka-config:
#    bootstrap-servers: localhost:9092
#    schema-registry-url-key: schema.registry.url
#    schema-registry-url: http://localhost:8081
#    topic-name: BENEFIT
#    topic-names-to-create:
#      - BENEFIT
#    num-of-partitions: 3
#    replication-factor: 3
#
#  kafka-consumer-config:
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#    consumer-group-id: benefit-topic-consumer
#    auto-offset-reset: earliest
#    specific-avro-reader-key: specific.avro.reader
#    specific-avro-reader: true
#    batch-listener: true
#    auto-startup: false
#    concurrency-level: 3
#    session-timeout-ms: 10000
#    heartbeat-interval-ms: 3000
#    max-poll-interval-ms: 300000
#    max-poll-records: 500
#    max-partition-fetch-bytes-default: 1048576
#    max-partition-fetch-bytes-boost-factor: 1
#    poll-timeout-ms: 150
lct-africa:
  notification:
    baseUrl: "http://localhost:8081/api/v1/notification"
    sms-endpoint: "/sms"
    email-attachment: "/mail/attachment"
    email-plain-endpoint: "/mail"
  member:
    search:
      url: "http://localhost:8070"
  claims:
    url: "http://localhost:8088"
    start_visit:
      url: "/lct/start_visit"
    get_open_transactions:
      url: "/lct/get_open_transactions"
    close_open_transaction:
      url: "/lct/close_open_transaction"
    agakhanNairobi: "/compas/lct/akuh/memberVerification/save_verified_lct_member"
  staging:
    url: "http://localhost:8080/api/v1/staging/claim"
  britam:
    url: "https://apitest.britam.com/MedicalClaims/ProxyServices/MedicalClaimsProxyServiceRS/claim"
  liaison:
    url: "http://192.168.0.26:8087/api/v1/lct/claims"
  document:
    url: "http://localhost:8095/api/file/download"


logging:
  level:
    org.zalando.logbook: TRACE
